#include <amxmodx>
#include <fakemeta>
#include <reapi>
#include <engine>

#include <jumpstats/global>
#include <jumpstats/front/cvars>
#include <jumpstats/front/cmds>
#include <jumpstats/forwards>
#include <jumpstats/front/menus>
#include <jumpstats/utils>
#include <jumpstats/front/prespeed>
#include <jumpstats/movestats>
#include <jumpstats/front/readyjumps>

#include <jumpstats/in_bhop_jumps>
#include <jumpstats/in_ducks>
#include <jumpstats/in_ladder>
